# Generated by Django 6.0.1 on 2026-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_type',
            field=models.CharField(choices=[('A', 'Неделя А (четн.)'), ('B', 'Неделя Б (неч.)'), ('BOTH', 'Обе недели')], max_length=4, verbose_name='Тип недели'),
        ),
    ]
