# Generated by Django 6.0.1 on 2026-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_timeslot_alter_lesson_start_time_lesson_time_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
    ]
