# Generated by Django 6.0.1 on 2026-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_group_options_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subgroup',
            field=models.IntegerField(default=0, help_text='0 - вся группа, 1 - подгруппа 1, 2 - подгруппа 2', verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_group_per_course'),
        ),
    ]
