# Generated by Django 6.0.1 on 2026-05-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_lesson_subgroup_alter_group_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('GROUP', 'Группа'), ('SUBGROUP', 'Подгруппа')], max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вид группы',
                'verbose_name_plural': 'Виды групп',
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='lesson',
            name='denomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule.groupdenomination', verbose_name='Вид группы'),
        ),
    ]
