# Generated by Django 6.0.1 on 2026-05-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_groupdenomination_remove_lesson_subgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GroupDenominationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип группы',
                'verbose_name_plural': 'Типы групп',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
            },
        ),
        migrations.CreateModel(
            name='WeekType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип недели',
                'verbose_name_plural': 'Типы недель',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day__number', 'start_time'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='schedule.dayofweek', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='groupdenomination',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.groupdenominationtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.lessontype', verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.weektype', verbose_name='Тип недели'),
        ),
    ]
