# Generated by Django 6.0.1 on 2026-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_group_options_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
